name: DeathCounter
main: net.krinsoft.deathcounter.DeathCounter
version: 0.2.2
authors: [krinsdeath]
depend: []

commands:
    deathcount:
        description: 
        usage: |
            /<command> help           - display this message
            /<command> leaders [num]  - display the leaderboards for total kills
            /<command> [mob] [num]    - display the specified number of leaders for the specified monster
            /<command> reset [player] - reset the specified player to 0 for all stats